package com.wmd.kroplayer.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wmd.kroplayer.bean.VideoPlayHistoryBean;

import com.wmd.kroplayer.database.VideoPlayHistoryBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig videoPlayHistoryBeanDaoConfig;

    private final VideoPlayHistoryBeanDao videoPlayHistoryBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        videoPlayHistoryBeanDaoConfig = daoConfigMap.get(VideoPlayHistoryBeanDao.class).clone();
        videoPlayHistoryBeanDaoConfig.initIdentityScope(type);

        videoPlayHistoryBeanDao = new VideoPlayHistoryBeanDao(videoPlayHistoryBeanDaoConfig, this);

        registerDao(VideoPlayHistoryBean.class, videoPlayHistoryBeanDao);
    }
    
    public void clear() {
        videoPlayHistoryBeanDaoConfig.clearIdentityScope();
    }

    public VideoPlayHistoryBeanDao getVideoPlayHistoryBeanDao() {
        return videoPlayHistoryBeanDao;
    }

}
